@startuml Domain model

component Infrastructure{

    class User {
        UserID
        Credentials

        Create(UserID, Credentials)
        CreateHousehold(Name)
        ShareHousehold(Name, UserID)
        AcceptHouseholdShare(Name)
        DeleteHousehold(Name)
    }

    class PermissionToManageHousehold{
        UserID,
        HouseholdName,
        Active
    }

    User "1"->"*" PermissionToManageHousehold : has

}

component "Assets base" as AssetBase{

    class Household{
        Name

        Create(Name)
        CreateAssetType(Name, TypicalLifecycle?)
        CreateAsset(Name, AssetType, Lifecycle?)
    }

    class AssetType{
        Name
        TypicalLifecycle

        SetName(Name)
        SetTypicalLifecycle(TypicalLifecycle)
        Deprecate()
    }


    class Asset{
        AssetID
        Name
        Lifecycle

        SetName(Name)
        SetLifecycle(Lifecycle)
        Remove()
    }

    Household "1"==>"1..*" AssetType: uses classification
    Household *--> Asset
    Asset "*" -> "1" AssetType : grouped by
}


Household "1" <.left. "*" PermissionToManageHousehold : allows to operate

@enduml