@startuml Domain model

component "User Service"{

    class User {
        UserID
        Email
        Name
        --
        {static} Create(Email, Name)
        {static} FindByEmail(Email)
        Update(Name)
        --
        CreateHousehold(Name)
        ShareHousehold(Household, User)
        AcceptHouseholdShare(Household)
        DeleteHousehold(Household)
    }

    class PermissionToManageHousehold{
        UserID,
        HouseholdId,
        Active
    }

    User "1"->"*" PermissionToManageHousehold : has

}

component "Asset Service" as AssetBase{

    class Household{
        HouseholdId
        Name

        SetName(Name)
        CreateAssetType(Name, TypicalLifecycle?)
        CreateAsset(Name, AssetType, Lifecycle?)
    }

    class AssetType{
        AssetTypeId
        HouseholdId
        Name
        TypicalLifecycle

        SetName(Name)
        SetTypicalLifecycle(TypicalLifecycle)
        Deprecate()
    }


    class Asset{
        AssetID
        Name
        Lifecycle

        SetName(Name)
        SetLifecycle(Lifecycle)
        Remove()
    }

    Household "1"==>"1..*" AssetType: uses classification
    Household *--> Asset
    Asset "*" -> "1" AssetType : grouped by
}


Household "1" <.left. "*" PermissionToManageHousehold : allows to operate

@enduml