version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  pamuserservice:
    image: ${DOCKER_REGISTRY-}pamuserservice
    build:
      context: .
      dockerfile: PAM.UserService/Dockerfile

