version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  userservice.pam:
    image: ${DOCKER_REGISTRY-}pamuserservice
    build:
      context: .
      dockerfile: PAM.UserService/Dockerfile
    links:
      - mongo

  assetservice.pam:
    image: ${DOCKER_REGISTRY-}pamassetservice
    build:
      context: .
      dockerfile: PAM.AssetService/Dockerfile
    links:
      - mongo


  pam:
    image: ${DOCKER_REGISTRY-}pamfrontend
    build:
      context: .
      dockerfile: PAM/Dockerfile
    links:
      - "userservice.pam"
      - "assetservice.pam"